// SPDX-License-Identifier: GPL-2.0-or-later
// Generated from OBS Studio 32.2.2 headers. See docs/third-party/OBS-NOTICE.txt.
/* automatically generated by rust-bindgen 0.72.1 */

pub const MAX_AV_PLANES: u32 = 8;
pub const OBS_SOURCE_VIDEO: u32 = 1;
pub const OBS_SOURCE_AUDIO: u32 = 2;
pub const OBS_SOURCE_ASYNC: u32 = 4;
pub const OBS_SOURCE_ASYNC_VIDEO: u32 = 5;
pub const OBS_SOURCE_CUSTOM_DRAW: u32 = 8;
pub const OBS_SOURCE_INTERACTION: u32 = 32;
pub const OBS_SOURCE_COMPOSITE: u32 = 64;
pub const OBS_SOURCE_DO_NOT_DUPLICATE: u32 = 128;
pub const OBS_SOURCE_DEPRECATED: u32 = 256;
pub const OBS_SOURCE_DO_NOT_SELF_MONITOR: u32 = 512;
pub const OBS_SOURCE_CAP_DISABLED: u32 = 1024;
pub const OBS_SOURCE_CAP_OBSOLETE: u32 = 1024;
pub const OBS_SOURCE_MONITOR_BY_DEFAULT: u32 = 2048;
pub const OBS_SOURCE_SUBMIX: u32 = 4096;
pub const OBS_SOURCE_CONTROLLABLE_MEDIA: u32 = 8192;
pub const OBS_SOURCE_CEA_708: u32 = 16384;
pub const OBS_SOURCE_SRGB: u32 = 32768;
pub const OBS_SOURCE_CAP_DONT_SHOW_PROPERTIES: u32 = 65536;
pub const OBS_SOURCE_REQUIRES_CANVAS: u32 = 131072;
pub const OBS_SOURCE_FRAME_LINEAR_ALPHA: u32 = 1;
pub const OBS_SOURCE_FLAG_UNUSED_1: u32 = 1;
pub const OBS_SOURCE_FLAG_FORCE_MONO: u32 = 2;
pub const gs_color_space_GS_CS_SRGB: gs_color_space = 0;
pub const gs_color_space_GS_CS_SRGB_16F: gs_color_space = 1;
pub const gs_color_space_GS_CS_709_EXTENDED: gs_color_space = 2;
pub const gs_color_space_GS_CS_709_SCRGB: gs_color_space = 3;
pub type gs_color_space = ::std::os::raw::c_int;
pub type gs_effect_t = u8;
pub const audio_format_AUDIO_FORMAT_UNKNOWN: audio_format = 0;
pub const audio_format_AUDIO_FORMAT_U8BIT: audio_format = 1;
pub const audio_format_AUDIO_FORMAT_16BIT: audio_format = 2;
pub const audio_format_AUDIO_FORMAT_32BIT: audio_format = 3;
pub const audio_format_AUDIO_FORMAT_FLOAT: audio_format = 4;
pub const audio_format_AUDIO_FORMAT_U8BIT_PLANAR: audio_format = 5;
pub const audio_format_AUDIO_FORMAT_16BIT_PLANAR: audio_format = 6;
pub const audio_format_AUDIO_FORMAT_32BIT_PLANAR: audio_format = 7;
pub const audio_format_AUDIO_FORMAT_FLOAT_PLANAR: audio_format = 8;
pub type audio_format = ::std::os::raw::c_int;
pub const speaker_layout_SPEAKERS_UNKNOWN: speaker_layout = 0;
pub const speaker_layout_SPEAKERS_MONO: speaker_layout = 1;
pub const speaker_layout_SPEAKERS_STEREO: speaker_layout = 2;
pub const speaker_layout_SPEAKERS_2POINT1: speaker_layout = 3;
pub const speaker_layout_SPEAKERS_4POINT0: speaker_layout = 4;
pub const speaker_layout_SPEAKERS_4POINT1: speaker_layout = 5;
pub const speaker_layout_SPEAKERS_5POINT1: speaker_layout = 6;
pub const speaker_layout_SPEAKERS_7POINT1: speaker_layout = 8;
pub type speaker_layout = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct audio_output_data {
    pub data: [*mut f32; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of audio_output_data"][::std::mem::size_of::<audio_output_data>() - 64usize];
    ["Alignment of audio_output_data"][::std::mem::align_of::<audio_output_data>() - 8usize];
    ["Offset of field: audio_output_data::data"]
        [::std::mem::offset_of!(audio_output_data, data) - 0usize];
};
impl Default for audio_output_data {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct obs_data {
    _unused: [u8; 0],
}
pub type obs_data_t = obs_data;
pub const obs_combo_format_OBS_COMBO_FORMAT_INVALID: obs_combo_format = 0;
pub const obs_combo_format_OBS_COMBO_FORMAT_INT: obs_combo_format = 1;
pub const obs_combo_format_OBS_COMBO_FORMAT_FLOAT: obs_combo_format = 2;
pub const obs_combo_format_OBS_COMBO_FORMAT_STRING: obs_combo_format = 3;
pub const obs_combo_format_OBS_COMBO_FORMAT_BOOL: obs_combo_format = 4;
pub type obs_combo_format = ::std::os::raw::c_int;
pub const obs_combo_type_OBS_COMBO_TYPE_INVALID: obs_combo_type = 0;
pub const obs_combo_type_OBS_COMBO_TYPE_EDITABLE: obs_combo_type = 1;
pub const obs_combo_type_OBS_COMBO_TYPE_LIST: obs_combo_type = 2;
pub const obs_combo_type_OBS_COMBO_TYPE_RADIO: obs_combo_type = 3;
pub type obs_combo_type = ::std::os::raw::c_int;
pub const obs_path_type_OBS_PATH_FILE: obs_path_type = 0;
pub const obs_path_type_OBS_PATH_FILE_SAVE: obs_path_type = 1;
pub const obs_path_type_OBS_PATH_DIRECTORY: obs_path_type = 2;
pub type obs_path_type = ::std::os::raw::c_int;
pub const obs_text_type_OBS_TEXT_DEFAULT: obs_text_type = 0;
pub const obs_text_type_OBS_TEXT_PASSWORD: obs_text_type = 1;
pub const obs_text_type_OBS_TEXT_MULTILINE: obs_text_type = 2;
pub const obs_text_type_OBS_TEXT_INFO: obs_text_type = 3;
pub type obs_text_type = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct obs_properties {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct obs_property {
    _unused: [u8; 0],
}
pub type obs_properties_t = obs_properties;
pub type obs_property_t = obs_property;
#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Default, Copy, Clone)]
pub struct obs_mouse_event {
    pub _bindgen_opaque_blob: [u32; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of obs_mouse_event"][::std::mem::size_of::<obs_mouse_event>() - 12usize];
    ["Alignment of obs_mouse_event"][::std::mem::align_of::<obs_mouse_event>() - 4usize];
};
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Default, Copy, Clone)]
pub struct obs_key_event {
    pub _bindgen_opaque_blob: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of obs_key_event"][::std::mem::size_of::<obs_key_event>() - 32usize];
    ["Alignment of obs_key_event"][::std::mem::align_of::<obs_key_event>() - 8usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct obs_source {
    _unused: [u8; 0],
}
pub type obs_source_t = obs_source;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct obs_missing_files {
    _unused: [u8; 0],
}
pub type obs_missing_files_t = obs_missing_files;
pub const obs_source_type_OBS_SOURCE_TYPE_INPUT: obs_source_type = 0;
pub const obs_source_type_OBS_SOURCE_TYPE_FILTER: obs_source_type = 1;
pub const obs_source_type_OBS_SOURCE_TYPE_TRANSITION: obs_source_type = 2;
pub const obs_source_type_OBS_SOURCE_TYPE_SCENE: obs_source_type = 3;
pub type obs_source_type = ::std::os::raw::c_int;
pub const obs_icon_type_OBS_ICON_TYPE_UNKNOWN: obs_icon_type = 0;
pub const obs_icon_type_OBS_ICON_TYPE_IMAGE: obs_icon_type = 1;
pub const obs_icon_type_OBS_ICON_TYPE_COLOR: obs_icon_type = 2;
pub const obs_icon_type_OBS_ICON_TYPE_SLIDESHOW: obs_icon_type = 3;
pub const obs_icon_type_OBS_ICON_TYPE_AUDIO_INPUT: obs_icon_type = 4;
pub const obs_icon_type_OBS_ICON_TYPE_AUDIO_OUTPUT: obs_icon_type = 5;
pub const obs_icon_type_OBS_ICON_TYPE_DESKTOP_CAPTURE: obs_icon_type = 6;
pub const obs_icon_type_OBS_ICON_TYPE_WINDOW_CAPTURE: obs_icon_type = 7;
pub const obs_icon_type_OBS_ICON_TYPE_GAME_CAPTURE: obs_icon_type = 8;
pub const obs_icon_type_OBS_ICON_TYPE_CAMERA: obs_icon_type = 9;
pub const obs_icon_type_OBS_ICON_TYPE_TEXT: obs_icon_type = 10;
pub const obs_icon_type_OBS_ICON_TYPE_MEDIA: obs_icon_type = 11;
pub const obs_icon_type_OBS_ICON_TYPE_BROWSER: obs_icon_type = 12;
pub const obs_icon_type_OBS_ICON_TYPE_CUSTOM: obs_icon_type = 13;
pub const obs_icon_type_OBS_ICON_TYPE_PROCESS_AUDIO_OUTPUT: obs_icon_type = 14;
pub type obs_icon_type = ::std::os::raw::c_int;
pub const obs_media_state_OBS_MEDIA_STATE_NONE: obs_media_state = 0;
pub const obs_media_state_OBS_MEDIA_STATE_PLAYING: obs_media_state = 1;
pub const obs_media_state_OBS_MEDIA_STATE_OPENING: obs_media_state = 2;
pub const obs_media_state_OBS_MEDIA_STATE_BUFFERING: obs_media_state = 3;
pub const obs_media_state_OBS_MEDIA_STATE_PAUSED: obs_media_state = 4;
pub const obs_media_state_OBS_MEDIA_STATE_STOPPED: obs_media_state = 5;
pub const obs_media_state_OBS_MEDIA_STATE_ENDED: obs_media_state = 6;
pub const obs_media_state_OBS_MEDIA_STATE_ERROR: obs_media_state = 7;
pub type obs_media_state = ::std::os::raw::c_int;
pub type obs_source_enum_proc_t = ::std::option::Option<
    unsafe extern "C" fn(
        parent: *mut obs_source_t,
        child: *mut obs_source_t,
        param: *mut ::std::os::raw::c_void,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct obs_source_audio_mix {
    pub output: [audio_output_data; 6usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of obs_source_audio_mix"][::std::mem::size_of::<obs_source_audio_mix>() - 384usize];
    ["Alignment of obs_source_audio_mix"][::std::mem::align_of::<obs_source_audio_mix>() - 8usize];
    ["Offset of field: obs_source_audio_mix::output"]
        [::std::mem::offset_of!(obs_source_audio_mix, output) - 0usize];
};
impl Default for obs_source_audio_mix {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct obs_source_info {
    pub id: *const ::std::os::raw::c_char,
    pub type_: obs_source_type,
    pub output_flags: u32,
    pub get_name: ::std::option::Option<
        unsafe extern "C" fn(
            type_data: *mut ::std::os::raw::c_void,
        ) -> *const ::std::os::raw::c_char,
    >,
    pub create: ::std::option::Option<
        unsafe extern "C" fn(
            settings: *mut obs_data_t,
            source: *mut obs_source_t,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub destroy: ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void)>,
    pub get_width:
        ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> u32>,
    pub get_height:
        ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> u32>,
    pub get_defaults: ::std::option::Option<unsafe extern "C" fn(settings: *mut obs_data_t)>,
    pub get_properties: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> *mut obs_properties_t,
    >,
    pub update: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void, settings: *mut obs_data_t),
    >,
    pub activate: ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void)>,
    pub deactivate: ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void)>,
    pub show: ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void)>,
    pub hide: ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void)>,
    pub video_tick: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void, seconds: f32),
    >,
    pub video_render: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void, effect: *mut gs_effect_t),
    >,
    pub filter_video: ::std::option::Option<
        unsafe extern "C" fn(
            data: *mut ::std::os::raw::c_void,
            frame: *mut obs_source_frame,
        ) -> *mut obs_source_frame,
    >,
    pub filter_audio: ::std::option::Option<
        unsafe extern "C" fn(
            data: *mut ::std::os::raw::c_void,
            audio: *mut obs_audio_data,
        ) -> *mut obs_audio_data,
    >,
    pub enum_active_sources: ::std::option::Option<
        unsafe extern "C" fn(
            data: *mut ::std::os::raw::c_void,
            enum_callback: obs_source_enum_proc_t,
            param: *mut ::std::os::raw::c_void,
        ),
    >,
    pub save: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void, settings: *mut obs_data_t),
    >,
    pub load: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void, settings: *mut obs_data_t),
    >,
    pub mouse_click: ::std::option::Option<
        unsafe extern "C" fn(
            data: *mut ::std::os::raw::c_void,
            event: *const obs_mouse_event,
            type_: i32,
            mouse_up: bool,
            click_count: u32,
        ),
    >,
    pub mouse_move: ::std::option::Option<
        unsafe extern "C" fn(
            data: *mut ::std::os::raw::c_void,
            event: *const obs_mouse_event,
            mouse_leave: bool,
        ),
    >,
    pub mouse_wheel: ::std::option::Option<
        unsafe extern "C" fn(
            data: *mut ::std::os::raw::c_void,
            event: *const obs_mouse_event,
            x_delta: ::std::os::raw::c_int,
            y_delta: ::std::os::raw::c_int,
        ),
    >,
    pub focus:
        ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void, focus: bool)>,
    pub key_click: ::std::option::Option<
        unsafe extern "C" fn(
            data: *mut ::std::os::raw::c_void,
            event: *const obs_key_event,
            key_up: bool,
        ),
    >,
    pub filter_remove: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void, source: *mut obs_source_t),
    >,
    pub type_data: *mut ::std::os::raw::c_void,
    pub free_type_data:
        ::std::option::Option<unsafe extern "C" fn(type_data: *mut ::std::os::raw::c_void)>,
    pub audio_render: ::std::option::Option<
        unsafe extern "C" fn(
            data: *mut ::std::os::raw::c_void,
            ts_out: *mut u64,
            audio_output: *mut obs_source_audio_mix,
            mixers: u32,
            channels: usize,
            sample_rate: usize,
        ) -> bool,
    >,
    pub enum_all_sources: ::std::option::Option<
        unsafe extern "C" fn(
            data: *mut ::std::os::raw::c_void,
            enum_callback: obs_source_enum_proc_t,
            param: *mut ::std::os::raw::c_void,
        ),
    >,
    pub transition_start:
        ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void)>,
    pub transition_stop:
        ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void)>,
    pub get_defaults2: ::std::option::Option<
        unsafe extern "C" fn(type_data: *mut ::std::os::raw::c_void, settings: *mut obs_data_t),
    >,
    pub get_properties2: ::std::option::Option<
        unsafe extern "C" fn(
            data: *mut ::std::os::raw::c_void,
            type_data: *mut ::std::os::raw::c_void,
        ) -> *mut obs_properties_t,
    >,
    pub audio_mix: ::std::option::Option<
        unsafe extern "C" fn(
            data: *mut ::std::os::raw::c_void,
            ts_out: *mut u64,
            audio_output: *mut audio_output_data,
            channels: usize,
            sample_rate: usize,
        ) -> bool,
    >,
    pub icon_type: obs_icon_type,
    pub media_play_pause:
        ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void, pause: bool)>,
    pub media_restart:
        ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void)>,
    pub media_stop: ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void)>,
    pub media_next: ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void)>,
    pub media_previous:
        ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void)>,
    pub media_get_duration:
        ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> i64>,
    pub media_get_time:
        ::std::option::Option<unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> i64>,
    pub media_set_time: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void, miliseconds: i64),
    >,
    pub media_get_state: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> obs_media_state,
    >,
    pub version: u32,
    pub unversioned_id: *const ::std::os::raw::c_char,
    pub missing_files: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void) -> *mut obs_missing_files_t,
    >,
    pub video_get_color_space: ::std::option::Option<
        unsafe extern "C" fn(
            data: *mut ::std::os::raw::c_void,
            count: usize,
            preferred_spaces: *const gs_color_space,
        ) -> gs_color_space,
    >,
    pub filter_add: ::std::option::Option<
        unsafe extern "C" fn(data: *mut ::std::os::raw::c_void, source: *mut obs_source_t),
    >,
    pub get_dark_icon: ::std::option::Option<
        unsafe extern "C" fn(
            type_data: *mut ::std::os::raw::c_void,
        ) -> *const ::std::os::raw::c_char,
    >,
    pub get_light_icon: ::std::option::Option<
        unsafe extern "C" fn(
            type_data: *mut ::std::os::raw::c_void,
        ) -> *const ::std::os::raw::c_char,
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of obs_source_info"][::std::mem::size_of::<obs_source_info>() - 424usize];
    ["Alignment of obs_source_info"][::std::mem::align_of::<obs_source_info>() - 8usize];
    ["Offset of field: obs_source_info::id"][::std::mem::offset_of!(obs_source_info, id) - 0usize];
    ["Offset of field: obs_source_info::type_"]
        [::std::mem::offset_of!(obs_source_info, type_) - 8usize];
    ["Offset of field: obs_source_info::output_flags"]
        [::std::mem::offset_of!(obs_source_info, output_flags) - 12usize];
    ["Offset of field: obs_source_info::get_name"]
        [::std::mem::offset_of!(obs_source_info, get_name) - 16usize];
    ["Offset of field: obs_source_info::create"]
        [::std::mem::offset_of!(obs_source_info, create) - 24usize];
    ["Offset of field: obs_source_info::destroy"]
        [::std::mem::offset_of!(obs_source_info, destroy) - 32usize];
    ["Offset of field: obs_source_info::get_width"]
        [::std::mem::offset_of!(obs_source_info, get_width) - 40usize];
    ["Offset of field: obs_source_info::get_height"]
        [::std::mem::offset_of!(obs_source_info, get_height) - 48usize];
    ["Offset of field: obs_source_info::get_defaults"]
        [::std::mem::offset_of!(obs_source_info, get_defaults) - 56usize];
    ["Offset of field: obs_source_info::get_properties"]
        [::std::mem::offset_of!(obs_source_info, get_properties) - 64usize];
    ["Offset of field: obs_source_info::update"]
        [::std::mem::offset_of!(obs_source_info, update) - 72usize];
    ["Offset of field: obs_source_info::activate"]
        [::std::mem::offset_of!(obs_source_info, activate) - 80usize];
    ["Offset of field: obs_source_info::deactivate"]
        [::std::mem::offset_of!(obs_source_info, deactivate) - 88usize];
    ["Offset of field: obs_source_info::show"]
        [::std::mem::offset_of!(obs_source_info, show) - 96usize];
    ["Offset of field: obs_source_info::hide"]
        [::std::mem::offset_of!(obs_source_info, hide) - 104usize];
    ["Offset of field: obs_source_info::video_tick"]
        [::std::mem::offset_of!(obs_source_info, video_tick) - 112usize];
    ["Offset of field: obs_source_info::video_render"]
        [::std::mem::offset_of!(obs_source_info, video_render) - 120usize];
    ["Offset of field: obs_source_info::filter_video"]
        [::std::mem::offset_of!(obs_source_info, filter_video) - 128usize];
    ["Offset of field: obs_source_info::filter_audio"]
        [::std::mem::offset_of!(obs_source_info, filter_audio) - 136usize];
    ["Offset of field: obs_source_info::enum_active_sources"]
        [::std::mem::offset_of!(obs_source_info, enum_active_sources) - 144usize];
    ["Offset of field: obs_source_info::save"]
        [::std::mem::offset_of!(obs_source_info, save) - 152usize];
    ["Offset of field: obs_source_info::load"]
        [::std::mem::offset_of!(obs_source_info, load) - 160usize];
    ["Offset of field: obs_source_info::mouse_click"]
        [::std::mem::offset_of!(obs_source_info, mouse_click) - 168usize];
    ["Offset of field: obs_source_info::mouse_move"]
        [::std::mem::offset_of!(obs_source_info, mouse_move) - 176usize];
    ["Offset of field: obs_source_info::mouse_wheel"]
        [::std::mem::offset_of!(obs_source_info, mouse_wheel) - 184usize];
    ["Offset of field: obs_source_info::focus"]
        [::std::mem::offset_of!(obs_source_info, focus) - 192usize];
    ["Offset of field: obs_source_info::key_click"]
        [::std::mem::offset_of!(obs_source_info, key_click) - 200usize];
    ["Offset of field: obs_source_info::filter_remove"]
        [::std::mem::offset_of!(obs_source_info, filter_remove) - 208usize];
    ["Offset of field: obs_source_info::type_data"]
        [::std::mem::offset_of!(obs_source_info, type_data) - 216usize];
    ["Offset of field: obs_source_info::free_type_data"]
        [::std::mem::offset_of!(obs_source_info, free_type_data) - 224usize];
    ["Offset of field: obs_source_info::audio_render"]
        [::std::mem::offset_of!(obs_source_info, audio_render) - 232usize];
    ["Offset of field: obs_source_info::enum_all_sources"]
        [::std::mem::offset_of!(obs_source_info, enum_all_sources) - 240usize];
    ["Offset of field: obs_source_info::transition_start"]
        [::std::mem::offset_of!(obs_source_info, transition_start) - 248usize];
    ["Offset of field: obs_source_info::transition_stop"]
        [::std::mem::offset_of!(obs_source_info, transition_stop) - 256usize];
    ["Offset of field: obs_source_info::get_defaults2"]
        [::std::mem::offset_of!(obs_source_info, get_defaults2) - 264usize];
    ["Offset of field: obs_source_info::get_properties2"]
        [::std::mem::offset_of!(obs_source_info, get_properties2) - 272usize];
    ["Offset of field: obs_source_info::audio_mix"]
        [::std::mem::offset_of!(obs_source_info, audio_mix) - 280usize];
    ["Offset of field: obs_source_info::icon_type"]
        [::std::mem::offset_of!(obs_source_info, icon_type) - 288usize];
    ["Offset of field: obs_source_info::media_play_pause"]
        [::std::mem::offset_of!(obs_source_info, media_play_pause) - 296usize];
    ["Offset of field: obs_source_info::media_restart"]
        [::std::mem::offset_of!(obs_source_info, media_restart) - 304usize];
    ["Offset of field: obs_source_info::media_stop"]
        [::std::mem::offset_of!(obs_source_info, media_stop) - 312usize];
    ["Offset of field: obs_source_info::media_next"]
        [::std::mem::offset_of!(obs_source_info, media_next) - 320usize];
    ["Offset of field: obs_source_info::media_previous"]
        [::std::mem::offset_of!(obs_source_info, media_previous) - 328usize];
    ["Offset of field: obs_source_info::media_get_duration"]
        [::std::mem::offset_of!(obs_source_info, media_get_duration) - 336usize];
    ["Offset of field: obs_source_info::media_get_time"]
        [::std::mem::offset_of!(obs_source_info, media_get_time) - 344usize];
    ["Offset of field: obs_source_info::media_set_time"]
        [::std::mem::offset_of!(obs_source_info, media_set_time) - 352usize];
    ["Offset of field: obs_source_info::media_get_state"]
        [::std::mem::offset_of!(obs_source_info, media_get_state) - 360usize];
    ["Offset of field: obs_source_info::version"]
        [::std::mem::offset_of!(obs_source_info, version) - 368usize];
    ["Offset of field: obs_source_info::unversioned_id"]
        [::std::mem::offset_of!(obs_source_info, unversioned_id) - 376usize];
    ["Offset of field: obs_source_info::missing_files"]
        [::std::mem::offset_of!(obs_source_info, missing_files) - 384usize];
    ["Offset of field: obs_source_info::video_get_color_space"]
        [::std::mem::offset_of!(obs_source_info, video_get_color_space) - 392usize];
    ["Offset of field: obs_source_info::filter_add"]
        [::std::mem::offset_of!(obs_source_info, filter_add) - 400usize];
    ["Offset of field: obs_source_info::get_dark_icon"]
        [::std::mem::offset_of!(obs_source_info, get_dark_icon) - 408usize];
    ["Offset of field: obs_source_info::get_light_icon"]
        [::std::mem::offset_of!(obs_source_info, get_light_icon) - 416usize];
};
impl Default for obs_source_info {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Default, Copy, Clone)]
pub struct obs_audio_data {
    pub _bindgen_opaque_blob: [u64; 10usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of obs_audio_data"][::std::mem::size_of::<obs_audio_data>() - 80usize];
    ["Alignment of obs_audio_data"][::std::mem::align_of::<obs_audio_data>() - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct obs_source_audio {
    pub data: [*const u8; 8usize],
    pub frames: u32,
    pub speakers: speaker_layout,
    pub format: audio_format,
    pub samples_per_sec: u32,
    pub timestamp: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of obs_source_audio"][::std::mem::size_of::<obs_source_audio>() - 88usize];
    ["Alignment of obs_source_audio"][::std::mem::align_of::<obs_source_audio>() - 8usize];
    ["Offset of field: obs_source_audio::data"]
        [::std::mem::offset_of!(obs_source_audio, data) - 0usize];
    ["Offset of field: obs_source_audio::frames"]
        [::std::mem::offset_of!(obs_source_audio, frames) - 64usize];
    ["Offset of field: obs_source_audio::speakers"]
        [::std::mem::offset_of!(obs_source_audio, speakers) - 68usize];
    ["Offset of field: obs_source_audio::format"]
        [::std::mem::offset_of!(obs_source_audio, format) - 72usize];
    ["Offset of field: obs_source_audio::samples_per_sec"]
        [::std::mem::offset_of!(obs_source_audio, samples_per_sec) - 76usize];
    ["Offset of field: obs_source_audio::timestamp"]
        [::std::mem::offset_of!(obs_source_audio, timestamp) - 80usize];
};
impl Default for obs_source_audio {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Default, Copy, Clone)]
pub struct obs_source_frame {
    pub _bindgen_opaque_blob: [u64; 28usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of obs_source_frame"][::std::mem::size_of::<obs_source_frame>() - 224usize];
    ["Alignment of obs_source_frame"][::std::mem::align_of::<obs_source_frame>() - 8usize];
};
pub const obs_task_type_OBS_TASK_UI: obs_task_type = 0;
pub const obs_task_type_OBS_TASK_GRAPHICS: obs_task_type = 1;
pub const obs_task_type_OBS_TASK_AUDIO: obs_task_type = 2;
pub const obs_task_type_OBS_TASK_DESTROY: obs_task_type = 3;
pub type obs_task_type = ::std::os::raw::c_int;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_STREAMING_STARTING: obs_frontend_event = 0;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_STREAMING_STARTED: obs_frontend_event = 1;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_STREAMING_STOPPING: obs_frontend_event = 2;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_STREAMING_STOPPED: obs_frontend_event = 3;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_RECORDING_STARTING: obs_frontend_event = 4;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_RECORDING_STARTED: obs_frontend_event = 5;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_RECORDING_STOPPING: obs_frontend_event = 6;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_RECORDING_STOPPED: obs_frontend_event = 7;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_SCENE_CHANGED: obs_frontend_event = 8;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_SCENE_LIST_CHANGED: obs_frontend_event = 9;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_TRANSITION_CHANGED: obs_frontend_event = 10;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_TRANSITION_STOPPED: obs_frontend_event = 11;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_TRANSITION_LIST_CHANGED: obs_frontend_event = 12;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_SCENE_COLLECTION_CHANGED: obs_frontend_event = 13;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_SCENE_COLLECTION_LIST_CHANGED: obs_frontend_event =
    14;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_PROFILE_CHANGED: obs_frontend_event = 15;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_PROFILE_LIST_CHANGED: obs_frontend_event = 16;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_EXIT: obs_frontend_event = 17;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_REPLAY_BUFFER_STARTING: obs_frontend_event = 18;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_REPLAY_BUFFER_STARTED: obs_frontend_event = 19;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_REPLAY_BUFFER_STOPPING: obs_frontend_event = 20;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_REPLAY_BUFFER_STOPPED: obs_frontend_event = 21;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_STUDIO_MODE_ENABLED: obs_frontend_event = 22;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_STUDIO_MODE_DISABLED: obs_frontend_event = 23;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_PREVIEW_SCENE_CHANGED: obs_frontend_event = 24;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_SCENE_COLLECTION_CLEANUP: obs_frontend_event = 25;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_FINISHED_LOADING: obs_frontend_event = 26;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_RECORDING_PAUSED: obs_frontend_event = 27;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_RECORDING_UNPAUSED: obs_frontend_event = 28;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_TRANSITION_DURATION_CHANGED: obs_frontend_event =
    29;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_REPLAY_BUFFER_SAVED: obs_frontend_event = 30;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_VIRTUALCAM_STARTED: obs_frontend_event = 31;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_VIRTUALCAM_STOPPED: obs_frontend_event = 32;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_TBAR_VALUE_CHANGED: obs_frontend_event = 33;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_SCENE_COLLECTION_CHANGING: obs_frontend_event = 34;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_PROFILE_CHANGING: obs_frontend_event = 35;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_SCRIPTING_SHUTDOWN: obs_frontend_event = 36;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_PROFILE_RENAMED: obs_frontend_event = 37;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_SCENE_COLLECTION_RENAMED: obs_frontend_event = 38;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_THEME_CHANGED: obs_frontend_event = 39;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_SCREENSHOT_TAKEN: obs_frontend_event = 40;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_CANVAS_ADDED: obs_frontend_event = 41;
pub const obs_frontend_event_OBS_FRONTEND_EVENT_CANVAS_REMOVED: obs_frontend_event = 42;
pub type obs_frontend_event = ::std::os::raw::c_int;
